apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-config
  namespace: gym-management
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"                # Replace with your domain in production
  DJANGO_SETTINGS_MODULE: "GMS.settings"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "gymdb"
  STATIC_URL: "/static/"
  MEDIA_URL: "/media/"
