# Generated by Django 5.2.4 on 2025-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0009_equipment_category_equipment_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_contact",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="medical_conditions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_type",
            field=models.CharField(default="basic", max_length=20),
        ),
    ]
