# Generated by Django 5.2.4 on 2025-10-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0010_member_address_member_dob_member_emergency_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="additional_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="branch",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="enquiry_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="preferred_contact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
