# Generated by Django 6.0.2 on 2026-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_enquiry_additional_info_enquiry_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('join_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Full Day', 'Full Day')], default='Morning', max_length=20)),
                ('specialty', models.CharField(choices=[('Yoga', 'Yoga'), ('CrossFit', 'CrossFit'), ('Bodybuilding', 'Bodybuilding'), ('Weightlifting', 'Weightlifting'), ('Cardio', 'Cardio'), ('None', 'None')], default='None', max_length=50)),
            ],
        ),
    ]
