# Generated by Django 6.0.2 on 2026-03-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='member',
            name='medical_conditions',
        ),
    ]
