# Generated by Django 6.0.2 on 2026-03-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_remove_member_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
    ]
