# Generated by Django 5.2.6 on 2025-09-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
