# Generated by Django 5.2.4 on 2025-09-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_delete_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='initialamount',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='emailid',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='emailid',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='joindate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in days or months'),
        ),
    ]
