# Generated by Django 5.2.4 on 2025-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0008_alter_enquiry_id_alter_equipment_id_alter_member_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="equipment",
            name="condition",
            field=models.CharField(default="new", max_length=20),
        ),
        migrations.AddField(
            model_name="equipment",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="member",
            name="initialamount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
